#!/bin/bash

# Usage: block-snapshot add|remove img-file cow-file
#
# This creates dm-snapshot device on given arguments

SNAPSHOT_CHUNKSIZE=256  # same as in file.py

dir=$(dirname "$0")
if [ "$1" = "prepare" ] || [ "$1" = "cleanup" ]; then
  # shellcheck disable=SC1090,SC1091
  . "$dir/xen-hotplug-common.sh"
  command=$1
else
  # shellcheck disable=SC1090,SC1091
  . "$dir/block-common.sh"
fi

shopt -s nullglob

if [ -n "$XENBUS_PATH" ]; then
  HOTPLUG_STORE="/var/run/xen-hotplug/${XENBUS_PATH//\//-}"
fi

get_dev() {
  dev=$1

  if [ -L "$dev" ]; then
    dev=$(readlink -f "$dev") || fatal "$dev link does not exist."
  fi

  if [ -f "$dev" ]; then
    file=$dev

    # assign new loop device
    loopdev=$(losetup --find --nooverlap --show -- "$file" 2>/dev/null)
    if [ $? -ne 0 ] || [[ ! "$loopdev" =~ ^/dev/loop[0-9]+$ ]]
    then
      release_lock "block"
      fatal 'Failed to find an unused loop device'
    fi

    echo "$loopdev"
  else
    test -e "$dev" || fatal "$dev does not exist."
    test -b "$dev" || fatal "$dev is not a block device nor file."
    echo "$dev"
  fi
}

file_to_devname () {
  exec stat '--printf=-%D:%i' -- "$@"
}

create_dm_snapshot() {
  local base_dev cow_dev base_sz base cow dm_devname

  dm_devname=$1
  base=$2
  cow=$3

  if [ ! -e "/dev/mapper/$dm_devname" ]; then
    # prepare new snapshot device
    base_dev=$(get_dev "$base") && cow_dev=$(get_dev "$cow") || fatal 'get_dev failed'
    base_sz=$(blockdev --getsz "$base_dev")
    do_or_die dmsetup create "$dm_devname" --table "0 $base_sz snapshot $base_dev $cow_dev P $SNAPSHOT_CHUNKSIZE"
  fi

}

deps () {
  dmsetup -o blkdevname -- deps "$1" | cut -d: -f2 | sed -e 's#(\([a-z0-9-]\+\))#/dev/\1#g'
}

create_dm_snapshot_origin() {
  local base_dev base_sz dm_devname base

  dm_devname=$1
  base=$2

  if [ ! -e "/dev/mapper/$dm_devname" ]; then
    # prepare new snapshot-origin device
    base_dev=$(get_dev "$base")
    base_sz=$(blockdev --getsz "$base_dev")
    do_or_die dmsetup create "$dm_devname" --table "0 $base_sz snapshot-origin $base_dev"
  fi
}

is_unused () {
  dmsetup -- info "$1" 2>/dev/null|grep -Eq '^Open count: +0$'
}

in_use () {
  log info "Device $1 still in use - not removing"
  release_lock "block"
  exit 0
}

unset t
t=${0#*/}
case $t in
  (block-snapshot|block-origin) t=${t#block-};;
  (*) fatal "Bad script name $t";;
esac

setup_block_dev () {
  local t p base cow cow2 dm_devname_full
  t=$1 p=$2
  base=${p%%:*}
  cow=${p#*:}
  cow2=${p##*:}
  [ "$cow2" = "${base%.img}-cow.img" ] || fatal 'bad value for $cow2'
  if [ "$cow" != "$cow2" ]; then
    cow=${cow%:*}
  else
    cow2=""
  fi

  # first ensure that snapshot device exists (to write somewhere changes from snapshot-origin)
  dm_devname=snapshot$(file_to_devname "$base" "$cow")

  claim_lock "block"

  # prepare snapshot device
  create_dm_snapshot "$dm_devname" "$base" "$cow"

  if [ -n "$cow2" ]; then
    [ "$t" = 'snapshot' ] || fatal 'block-origin called with $cow2 set'
    dm_devname_full=$dm_devname$(file_to_devname "$cow2")
    create_dm_snapshot "$dm_devname_full" "/dev/mapper/$dm_devname" "$cow2"
    dm_devname="$dm_devname_full"
  else
    [ "$t" = 'origin' ] || fatal 'block-snapshot called without $cow2 set'
    # for origin - prepare snapshot-origin device and store its name
    dm_devname=origin$(file_to_devname "$base")
    create_dm_snapshot_origin "$dm_devname" "$base"
  fi
}

case "$command" in
  add)
    p=$(xenstore_read_default "$XENBUS_PATH/params" 'MISSING')
    if [ "$p" == "MISSING" ]; then
      fatal "Missing device parameters ($t $XENBUS_PATH/params)"
    fi
    echo "$p" > "$HOTPLUG_STORE-params"
    setup_block_dev "$t" "$p"
    xenstore_write "$XENBUS_PATH/node" "/dev/mapper/$dm_devname"
    echo "/dev/mapper/$dm_devname" > "$HOTPLUG_STORE-node"
    write_dev "/dev/mapper/$dm_devname"

    release_lock "block"
    exit 0
    ;;
  prepare)
    [ "$t" = "$2" ] || fatal 'Wrong block script called'
    setup_block_dev "$2" "$3"
    echo "/dev/mapper/$dm_devname"

    release_lock "block"
    exit 0
    ;;
  remove|cleanup)
    claim_lock "block"

    if [ "$command" = "cleanup" ]; then
      node=$3
    else
      node=$(cat "$HOTPLUG_STORE-node" 2> /dev/null)
    fi

    if [ -z "$node" ]; then
      #fatal "No device node to remove"
      #Most likely already removed
      exit 0
    fi

    if [ ! -e "$node" ]; then
      fatal "Device $node does not exist"
    elif ! is_unused "$node"; then
      in_use "$1"
    fi

    unset is_origin origin snapshot deps

    # get list of used (loop) devices
    deps=$(deps "$node")

    case $node in
      (/dev/mapper/snapshot-*)
        # do not remove snapshot if snapshot origin is still present
        if [ -e "${node/snapshot/origin}" ]; then in_use "$1"; fi
        ;;
      (/dev/mapper/origin-*)
        # remove unused snapshots
        for snap in "${node/origin/snapshot}-"*; do
          if is_unused "$snap"; then
            # unused snapshot - remove it
            deps+=" $(deps "$snap")"
            log debug "Removing $snap"
            dmsetup -- remove "$snap"
          fi
        done
        ;;
      (*)
        fatal "Bad name $node"
        ;;
    esac

    if [ -e "$node" ]; then
      log debug "Removing $node"
      dmsetup -- remove "$node"
    fi

    # try to free unused devices
    for dev in $deps; do
      if [ -b "$dev" ]; then
        log debug "Removing $dev"
        case $dev in
          /dev/loop*)
            losetup -d "$dev" 2> /dev/null || true
            ;;
          /dev/dm-*)
            dmsetup remove "$dev" 2> /dev/null || true
            ;;
        esac
      fi
    done

    if [ -n "$HOTPLUG_STORE" ]; then
      rm "$HOTPLUG_STORE-"*
    fi
    release_lock "block"

    exit 0
    ;;
esac

# vim:sw=2:et:
