#!/bin/bash

# Usage: block-snapshot add|remove img-file cow-file
#
# This creates dm-snapshot device on given arguments

SNAPSHOT_CHUNKSIZE=256  # same as in file.py

set -euo pipefail
shopt -s nullglob

fatal () {
  printf %s\\n "$@" >&2
  exit 1
}

get_dev() {
  dev=$1

  if [ -L "$dev" ]; then
    dev=$(readlink -f "$dev") || fatal "$dev link does not exist."
  fi

  if [ -f "$dev" ]; then
    file=$dev

    # assign new loop device
    loopdev=$(losetup --find --nooverlap --show -- "$file" 2>/dev/null)
    if [ $? -ne 0 ] || [[ ! "$loopdev" =~ ^/dev/loop[0-9]+$ ]]
    then
      fatal 'Failed to find an unused loop device'
    fi

    printf %s\\n "$loopdev"
  else
    test -e "$dev" || fatal "$dev does not exist."
    test -b "$dev" || fatal "$dev is not a block device nor file."
    printf %s\\n "$dev"
  fi
}

file_to_devname () {
  exec stat '--printf=-%D:%i' -- "$@"
}

create_dm_snapshot() {
  local base_dev cow_dev base_sz base cow dm_devname

  dm_devname=$1
  base=$2
  cow=$3

  if [ ! -e "/dev/mapper/$dm_devname" ]; then
    # prepare new snapshot device
    base_dev=$(get_dev "$base") || fatal "could not get loop device for $base"
    cow_dev=$(get_dev "$cow") || fatal "could not get loop device for $cow"
    base_sz=$(blockdev --getsz "$base_dev")
    3< "$base_dev" 4< "$cow_dev" dmsetup create "$dm_devname" \
      --table "0 $base_sz snapshot /dev/fd/3 /dev/fd/4 P $SNAPSHOT_CHUNKSIZE" ||
      fatal 'could not create snapshot'
  fi
}

create_dm_snapshot_origin() {
  local base_dev base_sz dm_devname base

  dm_devname=$1
  base=$2

  if [ ! -e "/dev/mapper/$dm_devname" ]; then
    # prepare new snapshot-origin device
    base_dev=$(get_dev "$base")
    base_sz=$(blockdev --getsz "$base_dev")
    3< "$base_dev" dmsetup create "$dm_devname" \
      --table "0 $base_sz snapshot-origin /dev/fd/3" ||
      fatal 'cound not create origin'
  fi
}

setup_block_dev () {
  local p base cow cow2 dm_devname_full
  base=$1 cow=$2 cow2=${3-}

  # first ensure that snapshot device exists (to write somewhere changes from snapshot-origin)
  dm_devname=snapshot$(file_to_devname "$base" "$cow")

  # prepare snapshot device
  create_dm_snapshot "$dm_devname" "$base" "$cow"

  if [ -n "${3+a}" ]; then
    dm_devname_full=$dm_devname$(file_to_devname "$cow2")
    create_dm_snapshot "$dm_devname_full" "/dev/mapper/$dm_devname" "$cow2"
    dm_devname="$dm_devname_full"
  else
    # for origin - prepare snapshot-origin device and store its name
    dm_devname=origin$(file_to_devname "$base")
    create_dm_snapshot_origin "$dm_devname" "$base"
  fi
}

if [[ "$#" -eq 2 ]] || [[ "$#" -eq 3 ]]; then
  setup_block_dev "$@"
else
  fatal "Wrong number of arguments (expected 2 or 3): $#"
fi

# vim:sw=2:et:
